### ISSUE TITLE
GTA5 label information

### ISSUE THREAD

**Issue by chrisliu54** [Wanger-SJTU/FCN-in-the-wild#1]
Hi, could you please show me how to find the label value in GTA5 to its corresponding name?
Specifically, how do you figure out the mapping from value to class name in `data/GTA5/data_utils.py`?

**Comment by Wanger-SJTU** [comment]
@chrisliu54 you could refers to [GTA5 dataset introduction](https://bitbucket.org/visinf/projects-2016-playing-for-data/overview).  The file is named  `initLabels.m`  in `projects-2016-playing-for-data\label` dir.
